export const flowerBouquets = [
  {
    _id: "1",
    en_name: "Get Well Soon Roses Bouquet",
    ar_name: "باقة ورود للشفاء العاجل",
    price: 200,
    image: "/images/Flower Bouquet/bouquet (1).jpg",
    category: {
      _id: "392841478219141934",
      name: "Bouquet",
      ar_name: "باقة زهور",
      slug: "bouquet",
    },
    en_description: "A beautiful arrangement of fresh roses to wish someone well.",
    ar_description: "ترتيب جميل من الورود الطازجة لتمني الشفاء العاجل لشخص ما.",
  },
  {
    _id: "2",
    en_name: "Fragrance Of The Day Flowers Vase",
    ar_name: "مزهرية عطر اليوم",
    price: 170,
    image: "/images/Flower Bouquet/bouquet (2).jpg",
    category: {
      _id: "392841478219141934",
      name: "Vase",
      ar_name: "مزهرية",
      slug: "vase",
    },
    en_description: "A fragrant vase of mixed flowers for any occasion.",
    ar_description: "مزهرية عطرة من الزهور المختلطة لأي مناسبة.",
  },
  {
    _id: "3",
    en_name: "Radiant Pink Flower Bouquet",
    ar_name: "باقة زهور وردية متألقة",
    price: 225,
    image: "/images/Flower Bouquet/bouquet (3).jpg",
    category: {
      _id: "392841478219141934",
      name: "Bouquet",
      ar_name: "باقة زهور",
      slug: "bouquet",
    },
    en_description: "Elegant pink bouquet to brighten someone's day.",
    ar_description: "باقة وردية أنيقة لإضفاء البهجة على يوم شخص ما.",
  },
  {
    _id: "4",
    en_name: "Gradient Roses Bouquet",
    ar_name: "باقة ورود متدرجة الألوان",
    price: 230,
    image: "/images/Flower Bouquet/bouquet (4).jpg",
    category: {
      _id: "392841478219141934",
      name: "Bouquet",
      ar_name: "باقة زهور",
      slug: "bouquet",
    },
    en_description: "A stunning gradient of roses wrapped with care.",
    ar_description: "تدرج رائع من الورود ملفوفة بعناية.",
  },
  {
    _id: "5",
    en_name: "Elegant Roses Symphony Bouquet",
    ar_name: "باقة سيمفونية الورود الأنيقة",
    price: 250,
    image: "/images/Flower Bouquet/bouquet (5).jpg",
    category: {
      _id: "392841478219141934",
      name: "Bouquet",
      ar_name: "باقة زهور",
      slug: "bouquet",
    },
    en_description: "A symphony of elegant roses, perfect for gifts.",
    ar_description: "سيمفونية من الورود الأنيقة، مثالية للهدايا.",
  },
  {
    _id: "6",
    en_name: "Elegant Red Flowers Vase",
    ar_name: "مزهرية زهور حمراء أنيقة",
    price: 350,
    image: "/images/Flower Bouquet/bouquet (6).jpg",
    category: {
      _id: "392841478219141934",
      name: "Vase",
      ar_name: "مزهرية",
      slug: "vase",
    },
    en_description: "Bright red flower arrangement in a stylish vase.",
    ar_description: "تنسيق زهور حمراء زاهية في مزهرية أنيقة.",
  },
  {
    _id: "7",
    en_name: "Gradient Roses Bouquet",
    ar_name: "باقة ورود متدرجة الألوان",
    price: 230,
    image: "/images/Flower Bouquet/bouquet (1).jpg",
    category: {
      _id: "392841478219141934",
      name: "Bouquet",
      ar_name: "باقة زهور",
      slug: "bouquet",
    },
    en_description: "A bouquet with gradient tones of roses.",
    ar_description: "باقة بتدرجات لونية من الورود.",
  },
  {
    _id: "8",
    en_name: "Radiant Pink Flower Bouquet",
    ar_name: "باقة زهور وردية متألقة",
    price: 225,
    image: "/images/Flower Bouquet/bouquet (2).jpg",
    category: {
      _id: "392841478219141934",
      name: "Bouquet",
      ar_name: "باقة زهور",
      slug: "bouquet",
    },
    en_description: "A pink bouquet to spread love and joy.",
    ar_description: "باقة وردية لنشر الحب والفرح.",
  },
];


// Reusable content for the “gift ideas” strip.
// Each item has English/Arabic labels so it works with your i18n too.
export const giftIdeas = [
  {
    id: "hand-bouquet",
    name_en: "Hand Bouquet",
    name_ar: "باقة يد",
    image: "/images/unique gifts/category (4).avif",
  },
  {
    id: "vase-flowers",
    name_en: "Flower in Vases",
    name_ar: "زهور في المزهريات",
    image: "/images/unique gifts/category (2).avif",
  },
  {
    id: "chocolate",
    name_en: "Chocolate",
    name_ar: "شوكولاتة",
    image: "/images/unique gifts/category (6).avif",
  },
  {
    id: "cake",
    name_en: "Cake",
    name_ar: "كيك",
    image: "/images/unique gifts/category (1).avif",
  },
  {
    id: "watches",
    name_en: "Watches",
    name_ar: "ساعات",
    image: "/images/unique gifts/category (8).avif",
  },
  {
    id: "teddy",
    name_en: "Teddy Bear",
    name_ar: "دب لعبة",
    image: "/images/unique gifts/category (7).png",
  },
];
